# Generated by Django 6.0.2 on 2026-02-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField()),
                ('Email', models.EmailField(max_length=254)),
                ('Age', models.IntegerField()),
                ('City', models.CharField()),
            ],
        ),
    ]
